name: FlameHubManager
author: TYSluukie
version: 0.1
main: me.tysluukie.flamepvpmanager.main

commands:
    help:
      usage: /<command>
      description: help
    setrank:
      usage: /<command> <player> <string>
      description: setrank
    hub:
      usage: /<command>
      description: hub
    kingdom:
      usage: /<command>
      description: kingdom
    gm:
      usage: /<command>
      description: gamemode
    spawn:
      usage: /<command>
      description: spawn
    setspawn:
      usage: /<command>
      description: setspawn
    startbroadcast:
      usage: /<command>
      description: startbroadcast
    stopbroadcast:
      usage: /<command>
      description: stopbroadcast
    announce:
      usage: /<command>
      description: announce
    shutdown:
      usage: /<command>
      description: shutdown